### ISSUE TITLE
Serial implementation of manual bot motion without feedback

### ISSUE THREAD

**Issue by adis98** [RoboManipal-9-0/Libraries#11]
**Task priority**
The priority of the task [HIGH]

**Task description**
Implementing the motion of Manual bot using Serial communication with a bluetooth module. Without feedback.

**Person assigned**
Task assigned to  [@adis98] 

# Must Haves
Things that **have** to be there in the library.

## Extras
Need to include feedback mechanism.

**Comment by TheProjectsGuy** [comment]
- Issue created in the wrong repository, please recreate this issue in the [Competitions repository](https://github.com/RoboManipal-9-0/Competitions). 
- If you're testing the Bluetooth communication library, then please rename this issue as soon as possible.
